### ISSUE TITLE
Hexo Blog shows Error on Configuration

### ISSUE THREAD

**Issue by adamzvolanek** [fletchto99/hexo-dev-docker#2]
The Hexo contain I am using is setup with the following container paths and variables:
![image](https://user-images.githubusercontent.com/80661527/182054889-69e68969-98a6-4a18-852e-1873280f39f3.png)

Upon launching to port 8080 I am greeted with a `Cannot GET /` message in my browser. 

I tried searching a few articles citing to add a '/' to the path in index_generator to no avail.
```
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
```

Issuing a hexo init <string> seems to work find spitting out a INFO status of:

> Start blogging with Hexo!

However port 8080 page status reads the same as above and docker directory remains empty: 
![image](https://user-images.githubusercontent.com/80661527/182055112-48842e84-d1fa-44f6-8a81-406083f7a45d.png)

Hoping to get some guidance or at least attention to the Unraid docker being provided.
